/**
 * Default UI strings (Italian).
 * The admin page /admin/translations lets users override these in any other language.
 * Public pages will use t(key) to render: override[lang] ?? base[key] ?? key.
 *
 * Add new keys here freely. Removing a key is OK too; orphaned overrides remain in DB
 * but won't be shown anywhere.
 */
export interface UiStringDef {
  key: string;
  defaultValue: string;
  description?: string;
}

export interface UiStringGroup {
  id: string;
  label: string;
  strings: UiStringDef[];
}

export const UI_STRING_GROUPS: UiStringGroup[] = [
  // ─── Generale (menu, footer, comuni, form) ────────────────────────────────
  {
    id: "menu",
    label: "Menu Header (mobile + desktop)",
    strings: [
      { key: "menu.products", defaultValue: "PRODOTTI" },
      { key: "menu.products.all", defaultValue: "TUTTI I PRODOTTI" },
      { key: "menu.products.complementi", defaultValue: "COMPLEMENTI" },
      { key: "menu.products.classici", defaultValue: "I CLASSICI" },
      { key: "menu.products.imbottiti", defaultValue: "IMBOTTITI" },
      { key: "menu.products.outdoor", defaultValue: "OUTDOOR" },
      { key: "menu.products.sedute", defaultValue: "SEDUTE" },
      { key: "menu.products.tavoli", defaultValue: "TAVOLI" },
      { key: "menu.projects", defaultValue: "PROGETTI" },
      { key: "menu.projects.all", defaultValue: "TUTTI I PROGETTI" },
      { key: "menu.projects.bistrot", defaultValue: "BISTROT & RESTAURANT" },
      { key: "menu.projects.hotellerie", defaultValue: "HOTELLERIE" },
      { key: "menu.projects.cultural", defaultValue: "SPAZI CULTURALI" },
      { key: "menu.projects.residential", defaultValue: "RESIDENZIALI" },
      { key: "menu.world", defaultValue: "MONDO GTV" },
      { key: "menu.world.manifesto", defaultValue: "BRAND MANIFESTO" },
      { key: "menu.world.heritage", defaultValue: "HERITAGE" },
      { key: "menu.world.wood", defaultValue: "LA CURVATURA DEL LEGNO" },
      { key: "menu.world.sustainability", defaultValue: "SOSTENIBILITÀ" },
      { key: "menu.world.designers", defaultValue: "DESIGNER E PREMI" },
      { key: "menu.world.experience", defaultValue: "GTV EXPERIENCE" },
      { key: "menu.campaigns", defaultValue: "CAMPAGNE & VIDEO" },
      { key: "menu.news", defaultValue: "NEWS & RASSEGNA STAMPA" },
      { key: "menu.professionals", defaultValue: "PROFESSIONISTI" },
      { key: "menu.professionals.custom", defaultValue: "REALIZZAZIONI CUSTOM" },
      { key: "menu.professionals.catalogs", defaultValue: "CATALOGHI" },
      { key: "menu.professionals.tech", defaultValue: "MATERIALE TECNICO" },
      { key: "menu.contact", defaultValue: "CONTATTI" },
      { key: "menu.contact.sales", defaultValue: "RETE DI VENDITA" },
      { key: "menu.contact.collab", defaultValue: "COLLABORAZIONI NUOVI DESIGNER" },
      { key: "menu.contact.press", defaultValue: "UFFICIO STAMPA" },
      { key: "menu.contact.info", defaultValue: "RICHIESTA INFORMAZIONI" },
      { key: "menu.contact.landing", defaultValue: "LANDING PAGE" },
    ],
  },
  {
    id: "nav",
    label: "Menu di navigazione (chiavi extra)",
    strings: [
      { key: "nav.home", defaultValue: "Home" },
      { key: "nav.products", defaultValue: "Prodotti" },
      { key: "nav.designers", defaultValue: "Designer" },
      { key: "nav.projects", defaultValue: "Progetti" },
      { key: "nav.campaigns", defaultValue: "Campagne e Video" },
      { key: "nav.news", defaultValue: "News e Rassegna stampa" },
      { key: "nav.world", defaultValue: "Mondo GTV" },
      { key: "nav.professionals", defaultValue: "Professionisti" },
      { key: "nav.contact", defaultValue: "Contatti" },
    ],
  },
  {
    id: "footer",
    label: "Footer",
    strings: [
      { key: "footer.copyright", defaultValue: "© Gebrüder Thonet Vienna" },
      { key: "footer.privacy", defaultValue: "Privacy Policy" },
      { key: "footer.cookies", defaultValue: "Cookie Policy" },
      { key: "footer.newsletter.title", defaultValue: "Per gli amanti del design" },
      { key: "footer.newsletter.subtitle", defaultValue: "Ricevi novità e ispirazioni in esclusiva." },
      { key: "footer.newsletter.button", defaultValue: "Iscriviti" },
      { key: "footer.newsletter.placeholder", defaultValue: "La tua email" },
      { key: "footer.newsletter.success", defaultValue: "Grazie per l'iscrizione!" },
      { key: "footer.newsletter.consent", defaultValue: "Accetto la" },
      { key: "footer.language", defaultValue: "Lingua" },
      { key: "footer.col.explore", defaultValue: "Esplora" },
      { key: "footer.col.info", defaultValue: "Informati" },
      { key: "footer.col.follow", defaultValue: "Seguici" },
      { key: "footer.terms", defaultValue: "Condizioni Generali di Vendita" },
      { key: "footer.company.headquarters", defaultValue: "Headquarters Gebrüder Thonet Vienna GmbH" },
      { key: "footer.company.registered", defaultValue: "Registered Office Gebrüder Thonet Vienna GmbH" },
      { key: "footer.company.licencee", defaultValue: "Offices of the trademarks licencee" },
      { key: "footer.bottom.copyright", defaultValue: "Copyright 2025 © GEBRUDER THONET VIENNA GMBH" },
      { key: "footer.bottom.disclaimer", defaultValue: "Si prega di osservare che l'utilizzo del marchio e il nome della società \"Gebrüder Thonet Vienna\" negli Stati Uniti e l'uso del marchio di fabbrica \"Gebrüder Thonet Vienna\" in Germania comporta restrizioni, a causa di accordi stipulati con altre imprese. Per ulteriori informazioni si prega di contattare info@gebruederthonetvienna.it." },
    ],
  },
  {
    id: "search",
    label: "Pannello ricerca",
    strings: [
      { key: "search.title", defaultValue: "Che cosa stai cercando?" },
      { key: "search.placeholder", defaultValue: "Scrivi qui la tua chiave di ricerca" },
      { key: "search.button", defaultValue: "Avvia la ricerca" },
      { key: "search.empty", defaultValue: "Nessun risultato trovato per" },
      { key: "search.group.products", defaultValue: "Prodotti" },
      { key: "search.group.projects", defaultValue: "Progetti" },
      { key: "search.group.designers", defaultValue: "Designer" },
      { key: "search.group.campaigns", defaultValue: "Campagne" },
      { key: "search.group.awards", defaultValue: "Premi" },
    ],
  },
  {
    id: "common",
    label: "Pulsanti / etichette comuni",
    strings: [
      { key: "common.discover", defaultValue: "Scopri di più" },
      { key: "common.discover_product", defaultValue: "Scopri il prodotto" },
      { key: "common.contact_us", defaultValue: "Contattaci" },
      { key: "common.read_more", defaultValue: "Leggi di più" },
      { key: "common.download", defaultValue: "Scarica" },
      { key: "common.view_all", defaultValue: "Vedi tutti" },
      { key: "common.search", defaultValue: "Cerca" },
      { key: "common.loading", defaultValue: "Caricamento…" },
      { key: "common.back", defaultValue: "Indietro" },
      { key: "common.close", defaultValue: "Chiudi" },
      { key: "common.share", defaultValue: "Condividi" },
      { key: "common.related", defaultValue: "Potrebbe interessarti anche" },
      { key: "common.breadcrumb_home", defaultValue: "Home" },
      { key: "common.discover_world", defaultValue: "Scopri il mondo GTV" },
      { key: "common.best_projects", defaultValue: "I migliori progetti" },
      { key: "common.discover_more", defaultValue: "Scopri di più" },
      { key: "common.menu_featured", defaultValue: "Interno Marche | Scopri il nostro flagship hotel" },
    ],
  },
  {
    id: "home",
    label: "Homepage (sezioni)",
    strings: [
      { key: "home.featured.label", defaultValue: "Nuovo prodotto" },
      { key: "home.featured.title", defaultValue: "Una silhouette\nmorbida\ne accogliente" },
      { key: "home.featured.cta", defaultValue: "Scopri il prodotto" },
      { key: "home.spotlight.label", defaultValue: "Icona del design" },
      { key: "home.spotlight.title", defaultValue: "L'eleganza\nsenza tempo\ndel legno curvato" },
      { key: "home.spotlight.cta", defaultValue: "Scopri il prodotto" },
      { key: "home.wood.title", defaultValue: "L'armonia del legno" },
      { key: "home.wood.cta", defaultValue: "Scopri l'arte del legno curvato" },
      { key: "home.banner.title", defaultValue: "Sedute che invitano a restare,\nmomenti che prendono forma" },
      { key: "home.banner.cta", defaultValue: "I migliori progetti" },
      { key: "home.born.title", defaultValue: "Born in Vienna.\nMade in Italy.\nDesigned around\nthe world." },
      { key: "home.categories.title", defaultValue: "Heritage designs the future" },
      { key: "home.categories.cta", defaultValue: "Scopri l'intera collezione" },
    ],
  },
  {
    id: "forms",
    label: "Form (contatti, registrazione, ecc.)",
    strings: [
      { key: "form.name", defaultValue: "Nome" },
      { key: "form.surname", defaultValue: "Cognome" },
      { key: "form.email", defaultValue: "Email" },
      { key: "form.phone", defaultValue: "Telefono" },
      { key: "form.company", defaultValue: "Azienda" },
      { key: "form.message", defaultValue: "Messaggio" },
      { key: "form.subject", defaultValue: "Oggetto" },
      { key: "form.privacy_consent", defaultValue: "Acconsento al trattamento dei miei dati personali." },
      { key: "form.send", defaultValue: "Invia" },
      { key: "form.success", defaultValue: "Messaggio inviato con successo." },
      { key: "form.error", defaultValue: "Si è verificato un errore. Riprova." },
      { key: "form.required", defaultValue: "Campo obbligatorio" },
    ],
  },
  // ─── Pagine pubbliche ─────────────────────────────────────────────────────
  {
    id: "mondo-gtv",
    label: "Mondo GTV (intro)",
    strings: [
      { key: "mondo-gtv.title", defaultValue: "Mondo GTV" },
      { key: "mondo-gtv.intro", defaultValue: "Mondo GTV racconta l'identità di Gebrüder Thonet Vienna: una tradizione che affonda le radici nella Vienna del XIX secolo e che oggi si rinnova attraverso la collaborazione con i più importanti studi di design internazionali. Esplora il manifesto del brand, la storia dell'azienda, la tecnica della curvatura del legno, l'impegno per la sostenibilità, i designer e i premi, fino all'esperienza di Interno Marche Design Hotel." },
      { key: "mondo-gtv.breadcrumb", defaultValue: "Mondo GTV" },
    ],
  },
  {
    id: "brand-manifesto",
    label: "Mondo GTV — Brand Manifesto",
    strings: [
      { key: "brand-manifesto.subtitle", defaultValue: "Brand manifesto" },
      { key: "brand-manifesto.title", defaultValue: "Born in Vienna.\nMade in Italy.\nDesigned around the world." },
      { key: "brand-manifesto.intro", defaultValue: "Ogni parola riflette una parte fondamentale della nostra essenza: la nostra origine storica, l'eccellenza artigianale e la nostra visione globale. Non è semplicemente un claim, ma un viaggio che attraversa il tempo, la cultura e le tradizioni, per raccontare un brand che nasce in un angolo dell'Europa, si esprime in un altro e si proietta verso il mondo intero. Ogni nostro prodotto è un simbolo di questa fusione: un'unione tra passato e futuro, artigianato e design contemporaneo, locale e globale." },
      { key: "brand-manifesto.heritage.label", defaultValue: "Our Heritage" },
      { key: "brand-manifesto.heritage.title", defaultValue: "Born in Vienna" },
      { key: "brand-manifesto.heritage.description", defaultValue: "La tradizione viennese, intrisa di arte e ingegno, è il nostro fondamento, un'eredità che ci accompagna in ogni creazione. Ma non ci fermiamo qui: il nostro sapere artigianale non è mai statico, evolve e si rinnova per raccontare storie nuove." },
      { key: "brand-manifesto.heritage.cta", defaultValue: "Le nostre origini →" },
      { key: "brand-manifesto.production.label", defaultValue: "La Produzione" },
      { key: "brand-manifesto.production.title", defaultValue: "Made in Italy" },
      { key: "brand-manifesto.production.description", defaultValue: "L'incontro perfetto tra la nostra eredità e la maestria artigianale italiana. In Italia, dove il design è un'arte quotidiana, ogni prodotto nasce dall'incontro di materiali pregiati e abilità artigianali che definiscono una qualità senza tempo. Qui, la bellezza si mescola con la funzionalità, creando pezzi che diventano iconici e resistenti, destinati a durare." },
      { key: "brand-manifesto.wood-harmony.title", defaultValue: "L'armonia del legno" },
      { key: "brand-manifesto.wood-harmony.cta", defaultValue: "Scopri l'arte del legno curvato →" },
      { key: "brand-manifesto.designers.label", defaultValue: "I Nostri Designer" },
      { key: "brand-manifesto.designers.title", defaultValue: "Designed around the world" },
      { key: "brand-manifesto.designers.description", defaultValue: "Collaboriamo con alcuni dei più grandi maestri del design contemporaneo, provenienti da culture e background diversi, per reinterpretare la nostra eredità con uno sguardo sempre nuovo. Ogni pezzo è il risultato di un dialogo tra passato e futuro, tra il saper fare artigianale e l'innovazione estetica, dando vita a collezioni che si inseriscono con naturalezza in contesti internazionali: un racconto che continua a evolversi, senza mai perdere la propria identità." },
      { key: "brand-manifesto.breadcrumb", defaultValue: "Brand Manifesto" },
    ],
  },
  {
    id: "heritage",
    label: "Mondo GTV — Heritage",
    strings: [
      { key: "heritage.title", defaultValue: "Le origini di \"Gebrüder Thonet\"" },
      { key: "heritage.family.alt", defaultValue: "Michael Thonet e i suoi cinque figli" },
      { key: "heritage.family.description", defaultValue: "Michael Thonet (1796-1871) e i suoi cinque figli furono i produttori di mobili di maggior successo dell'era industriale. Invitato dal cancelliere austriaco Metternich, che aveva visto i suoi prodotti all'Esposizione della Società degli Amici delle Arti di Coblenza, a sviluppare il proprio brevetto in Austria, nel 1842 Michael Thonet lasciò Boppard, in Germania, per stabilirsi a Vienna, dove nel 1853 fondò l'azienda \"Gebrüder Thonet\" coinvolgendo i suoi cinque figli." },
      { key: "heritage.innovation.title", defaultValue: "L'innovazione e il successo industriale" },
      { key: "heritage.innovation.p1", defaultValue: "Nella capitale dell'Impero asburgico, Michael Thonet passò dalla tecnica del legno lamellare incollato a quella del tondino incurvato a vapore, cioè a un processo chimico e meccanico di tipo industriale. Grazie a questa innovazione iniziò a produrre mobili in legno proponendo una collezione di forme eleganti e insieme razionali, con un procedimento che consentiva la produzione in grande serie. A questo si aggiunse subito, un sistema di distribuzione e di vendita in grado di penetrare qualsiasi mercato." },
      { key: "heritage.innovation.p2", defaultValue: "In quel periodo nacquero prodotti come la sedia \"N.1\" progettata per il famoso palazzo Schwarzenberg di Vienna, considerata la sedia \"tipo\" Thonet, da cui derivarono poi innumerevoli modelli fino alla sedia \"N.14\"." },
      { key: "heritage.expansion.title", defaultValue: "L'espansione e la trasformazione" },
      { key: "heritage.expansion.description", defaultValue: "Consapevolezza tecnologiche e di alto livello, diffusione dei prodotti e notorietà dell'azienda spinsero i più importanti architetti viennesi a progettare nuovi prodotti. Otto Wagner fece realizzare gli arredi per la Postsparkasse. Adolf Loos realizzò la sedia per il Café Museum e si dedicò alla progettazione del 1899." },
      { key: "heritage.postwar.p1", defaultValue: "Nel 1911 il catalogo Gebrüder Thonet contava 860 modelli distinti. Al termine della seconda guerra mondiale rimasero unità di produzione indipendenti in varie nazioni che acquistarono il nome diversi: in Austria, patria di Gebrüder Thonet, divenne Thonet-Mundus; da alcuni discendenti di Michael Thonet, figli Gebrüder Thonet e Richard Thonet. Dopo la guerra, diventava ricominciare da capo, con pochi pezzi che una passione e conoscenza per i mobili." },
      { key: "heritage.postwar.p2", defaultValue: "Gebrüder Thonet Vienna nasce proprio dai vecchi magazzini di Gebrüder Thonet, a partire dal 1948. Ricostruita, Richard e Gebrüder Thonet edificarono un stabilimento a Rethway, Steiermark, prima di realizzare il loro sito produttivo a Friedberg in 1952." },
      { key: "heritage.postwar.p3", defaultValue: "Nel 1976 la società cambiò nome in Gebrüder Thonet Vienna." },
      { key: "heritage.today.title", defaultValue: "Gebrüder Thonet Vienna oggi: tradizione e innovazione" },
      { key: "heritage.today.p1", defaultValue: "Recentemente Gebrüder Thonet Vienna GmbH (GTV) ha sviluppato la propria attività fra tradizione e innovazione, continuità e rinnovamento, dando vita a un programma di produzione articolato, che si propone in primo luogo di recuperare in forma di riedizione una serie di oggetti storici creati dalla Gebrüder Thonet." },
      { key: "heritage.today.p2", defaultValue: "GTV incarna l'arredamento contemporaneo, unendo tradizione e innovazione. Tecniche avanzate, materiali innovativi e design contemporaneo caratterizzano i suoi progetti, trasformando l'eredità classica in nuove soluzioni. Icone come la sedia N14, con oltre 50 milioni di esemplari prodotti, continuano a ispirare. GTV guarda al futuro, reinterpretando il passato per creare collezioni attuali e versatili." },
      { key: "heritage.coin.title", defaultValue: "La \"Moneta\" GTV" },
      { key: "heritage.coin.description", defaultValue: "L'inimitabile valore, materiale e immateriale nella struttura di ogni singolo pezzo: un particolare emblema che ne attesta autenticità, originalità e qualità e acquisito stabilità fra industria e sapiente artigianato, fra l'eredità del passato e l'esecuzione dettagliata, la moneta con l'effigie del marchio, che storicamente si apponeva internamente ai siti produttivi Thonet, appare in tutte le produzioni." },
      { key: "heritage.breadcrumb", defaultValue: "Heritage" },
    ],
  },
  {
    id: "curvatura-legno",
    label: "Mondo GTV — La Curvatura del Legno",
    strings: [
      { key: "curvatura-legno.title", defaultValue: "La curvatura del legno" },
      { key: "curvatura-legno.intro", defaultValue: "La tecnica della curvatura del legno è un metodo antico, presente nell'artigianato di diverse civiltà, ma rimasto a lungo in secondo piano a causa del suo limitato vantaggio in termini di produttività." },
      { key: "curvatura-legno.technique.title", defaultValue: "La Tecnica" },
      { key: "curvatura-legno.technique.p1", defaultValue: "L'intuizione di Michael Thonet nacque dall'osservazione che il legno fresco è più flessibile di quello secco. Partendo da questa considerazione, Thonet e alcuni suoi contemporanei sperimentarono la curvatura di pacchetti di sottili fogli di legno, immersi in colla bollente e poi asciugati in forme rigide." },
      { key: "curvatura-legno.technique.p2", defaultValue: "Tuttavia, questa soluzione non garantiva la resistenza del prodotto a causa della fragilità dell'adesivo. Per superare questo problema, Thonet decise di lavorare esclusivamente sulle proprietà fisiche del legno, eliminando completamente la colla dai suoi processi. Per ottenere una maggiore flessibilità del materiale — anche dopo l'essiccamento — aumentò la scivolosità tra le fibre esponendole in un ambiente altamente umido." },
      { key: "curvatura-legno.patent.title", defaultValue: "Il Brevetto" },
      { key: "curvatura-legno.patent.p1", defaultValue: "Nel 1842, Michael Thonet brevettò il processo che lo rese famoso in tutto il mondo: le strisce di legno (preferibilmente faggio, grazie alla sua fibra lunga, regolare e senza nodi) venivano tornite, poste in autoclave per assorbire umidità, piegate con forza e fissate in stampi metallici, per poi essere essiccate. Dopo la finitura dei pezzi, veniva assemblata la \"sedia di Vienna\", un elemento distintivo dell'azienda." },
      { key: "curvatura-legno.patent.p2", defaultValue: "Un vero e proprio processo industriale, accompagnato dalla progressiva eliminazione di ornamenti e giunzioni, a favore di linee rigorose e di una maggiore semplificazione degli elementi di assemblaggio." },
      { key: "curvatura-legno.conclusion", defaultValue: "Eleganza formale, solidità e leggerezza hanno decretato il successo dell'azienda, che in pochi anni ha aperto stabilimenti produttivi in tutto il mondo. Un metodo di produzione unico, radicato in una storia ricca di ispirazioni, che oggi si rinnova attraverso la scelta di materiali di alta qualità. I legni, selezionati per resistenza e versatilità, si combinano con tessuti pregiati, arricchendo la collezione con raffinate sfumature cromatiche." },
      { key: "curvatura-legno.breadcrumb", defaultValue: "La Curvatura del Legno" },
    ],
  },
  {
    id: "sostenibilita",
    label: "Mondo GTV — Sostenibilità",
    strings: [
      { key: "sostenibilita.title", defaultValue: "Sostenibilità" },
      { key: "sostenibilita.subtitle", defaultValue: "La tutela ambientale: una sfida per il futuro, un'opportunità per GTV." },
      { key: "sostenibilita.intro.p1", defaultValue: "Anno dopo anno, GTV ha sviluppato una crescente sensibilità verso le tematiche ambientali e, nell'ottica di un miglioramento continuo, aderisce alle normative che privilegiano l'uso di processi e materiali sostenibili. Un segno tangibile, un punto fermo che traccia un percorso orientato alla continuità, anche etica, tra il ciclo produttivo e il prodotto." },
      { key: "sostenibilita.intro.p2", defaultValue: "Un impegno concreto da parte dell'azienda per offrire garanzie reali in termini di sostenibilità ambientale e tutela della salute dei consumatori, con l'obiettivo di costruire un rapporto di fiducia basato su un approccio integrato allo sviluppo sostenibile." },
      { key: "sostenibilita.fsc.title", defaultValue: "Legno Certificato FSC (C123220)" },
      { key: "sostenibilita.fsc.p1", defaultValue: "Per la realizzazione delle proprie collezioni, Gebrüder Thonet Vienna GmbH sceglie di utilizzare legno certificato FSC (Forest Stewardship Council), il principale sistema internazionale di certificazione che garantisce la provenienza del legno da foreste gestite secondo rigorosi standard ambientali, sociali ed economici." },
      { key: "sostenibilita.fsc.p2", defaultValue: "Oltre a questa scelta, GTV adotta lavorazioni meno visibili ma altrettanto fondamentali per la sostenibilità. L'azienda ha infatti avviato la conversione del processo di verniciatura, sostituendo le vernici poliuretaniche con vernici a base d'acqua, riducendo così le emissioni in atmosfera e garantendo una maggiore tutela per il personale coinvolto." },
      { key: "sostenibilita.fsc.p3", defaultValue: "Nel 2021, GTV ha inaugurato un nuovo progetto Green, introducendo prodotti interamente sostenibili, tra cui la nuova sedia Beaulieu, progettata con un'attenzione particolare alla sostenibilità." },
      { key: "sostenibilita.breadcrumb", defaultValue: "Sostenibilità" },
    ],
  },
  {
    id: "designer-premi",
    label: "Mondo GTV — Designer e Premi",
    strings: [
      { key: "designer-premi.title", defaultValue: "Designer e premi" },
      { key: "designer-premi.intro", defaultValue: "GTV collabora con designer di talento per reinterpretare la tradizione attraverso un linguaggio contemporaneo. Questo impegno nella ricerca e nell'innovazione è riconosciuto a livello internazionale, con premi e menzioni che attestano l'eccellenza del brand nel design." },
      { key: "designer-premi.designers.title", defaultValue: "Designer" },
      { key: "designer-premi.awards.title", defaultValue: "Premi" },
      { key: "designer-premi.breadcrumb", defaultValue: "Designer e premi" },
      { key: "designer-premi.load_more", defaultValue: "Carica altri designer" },
    ],
  },
  {
    id: "designers-detail",
    label: "Pagina Designer (singolo)",
    strings: [
      { key: "designers.detail.products", defaultValue: "Prodotti" },
      { key: "designers.detail.visit_website", defaultValue: "Visita il sito →" },
      { key: "designers.detail.not_found", defaultValue: "Designer non trovato" },
      { key: "designers.detail.back", defaultValue: "Torna ai designer" },
    ],
  },
  {
    id: "gtv-experience",
    label: "Mondo GTV — GTV Experience",
    strings: [
      { key: "gtv-experience.hero.title", defaultValue: "GTV Experience\nInterno Marche Design Hotel" },
      { key: "gtv-experience.intro.title", defaultValue: "GTV arreda gli spazi\nprestigiosi di Interno Marche" },
      { key: "gtv-experience.intro.p1", defaultValue: "Gebrüder Thonet Vienna GmbH (GTV) arreda gli spazi prestigiosi di Interno Marche, il primo Design Experience Hotel che racconta la storia di 100 anni di storia del design. Nel centro delle Marche, in un bellissimo scenario di piccoli borghi e dolci colline, nasce l'hotel dei sogni di Franco Moschini, patron e attuale presidente di Gebrüder Thonet Vienna. Michele De Lucchi, GamFratesi, Vico Magistretti, Front e Nendo sono alcuni dei nomi celebri di architetti e designer che hanno collaborato con GTV e a cui si ispirano alcune delle stanze del design hotel, arricchite dalle loro opere più iconiche." },
      { key: "gtv-experience.intro.p2", defaultValue: "Protagonisti degli spazi raffinati come la lobby, il lounge bar e il patio, alcune delle creazioni più famose e contemporanee del brand, come la lounge Loie di Chiara Andreatti e il divano Targa di GamFratesi insieme al tavolino Arch Coffee Table di Front. La sedia Ample e i tavoli da bistrot, disegnati da Nichetto Studio, ricreano l'inconfondibile atmosfera raffinata del bistrot viennese storico, arredando il ristorante e il patio con la nuova versione outdoor della famiglia Ample. Con questa prestigiosa fornitura, Gebrüder Thonet Vienna si riconferma partner ideale per progetti contract sofisticati in tutto il mondo, grazie all'eleganza raffinata delle linee e all'alta qualità del design delle sue creazioni." },
      { key: "gtv-experience.stories.title", defaultValue: "Storie, visioni, ispirazioni" },
      { key: "gtv-experience.stories.description", defaultValue: "Interno Marche è il frutto di una visione che intreccia storia, arte e design. Un viaggio alla scoperta di Villa Gabrielli, una dimora storica nel cuore delle colline marchigiane, dove ogni scelta materica e di arredo racconta la stessa passione per l'eccellenza." },
      { key: "gtv-experience.villa.title", defaultValue: "La rinascita di Villa Gabrielli" },
      { key: "gtv-experience.villa.description", defaultValue: "Villa Gabrielli, un gioiello tardo Liberty, simbolo dello sviluppo della città di Tolentino nel secolo scorso. Nel 1922, l'edificio era inizialmente una fabbrica e la residenza dell'imprenditore Nazareno Gabrielli, creatore del famoso marchio di moda italiano. Dopo di lui, divenne il primo sito produttivo della nuova Poltrona Frau e la residenza di Franco Moschini. Il patrimonio del luogo è conservato nel progetto Interno Marche, che ha ripensato e ricreato con cura questi spazi di lavoro, famiglia, vita vissuta e li ha così restituiti alla città." },
      { key: "gtv-experience.lobby.title", defaultValue: "Lobby" },
      { key: "gtv-experience.lobby.description", defaultValue: "Il Foyer è il punto di arrivo e partenza, un ambiente espressivo e di grande impatto, dove le sedute iconiche di GTV accolgono gli ospiti in un'atmosfera sospesa tra classico e contemporaneo." },
      { key: "gtv-experience.corridors.title", defaultValue: "I corridoi" },
      { key: "gtv-experience.corridors.description", defaultValue: "I corridoi diventano spazi espositivi, gallerie intime dove le creazioni GTV punteggiano il percorso, trasformando il semplice passaggio in un'esperienza estetica. Pezzi di design che dialogano con le superfici e la luce naturale." },
      { key: "gtv-experience.rooms.title", defaultValue: "30 camere iconiche." },
      { key: "gtv-experience.live.title", defaultValue: "Vivi la GTV Experience" },
      { key: "gtv-experience.live.description", defaultValue: "Interno Marche è un invito a vivere il design nella sua dimensione più autentica. Scopri il fascino delle collezioni GTV immerse in un contesto unico, dove ogni stanza racconta una storia diversa e ogni dettaglio è pensato per emozionare." },
      { key: "gtv-experience.breadcrumb", defaultValue: "GTV Experience" },
    ],
  },
  {
    id: "prodotti",
    label: "Pagina Prodotti",
    strings: [
      { key: "prodotti.title", defaultValue: "Prodotti" },
      { key: "prodotti.description", defaultValue: "I prodotti Gebrüder Thonet Vienna uniscono tradizione e innovazione in forme iconiche e senza tempo. Leggerezza visiva, solidità e dettagli artigianali rendono ogni pezzo unico, ideale per spazi residenziali e contract. Personalizzabili in finiture e materiali, portano eleganza e carattere in ogni ambiente." },
      { key: "prodotti.filter.all", defaultValue: "Tutti" },
      { key: "prodotti.filter.designer", defaultValue: "Designer" },
      { key: "prodotti.filter.category", defaultValue: "Categoria" },
      { key: "prodotti.empty", defaultValue: "Nessun prodotto trovato per questa selezione." },
      { key: "prodotti.detail.materials", defaultValue: "Materiali" },
      { key: "prodotti.detail.dimensions", defaultValue: "Dimensioni" },
      { key: "prodotti.detail.designer", defaultValue: "Designer" },
      { key: "prodotti.detail.year", defaultValue: "Anno" },
      { key: "prodotti.detail.tech_sheet", defaultValue: "Scheda tecnica" },
      { key: "prodotti.detail.request_info", defaultValue: "Richiedi informazioni" },
      { key: "prodotti.breadcrumb", defaultValue: "Prodotti" },
      { key: "prodotti.detail.nav.inspiration", defaultValue: "Ispirazione" },
      { key: "prodotti.detail.nav.designer", defaultValue: "Designer" },
      { key: "prodotti.detail.nav.specs", defaultValue: "Specifiche Tecniche" },
      { key: "prodotti.detail.nav.projects", defaultValue: "Progetti" },
      { key: "prodotti.detail.pcon.title", defaultValue: "Prodotto" },
      { key: "prodotti.detail.designer.label", defaultValue: "Designer" },
      { key: "prodotti.detail.designer.cta", defaultValue: "Vai alla scheda →" },
      { key: "prodotti.detail.docs.unavailable", defaultValue: "Documentazione non ancora disponibile." },
      { key: "prodotti.detail.discover_more", defaultValue: "Scopri di più →" },
      { key: "prodotti.detail.projects.label", defaultValue: "Progetti" },
      { key: "prodotti.detail.projects.title", defaultValue: "Gli ambienti si vestono di eleganza con {name}" },
      { key: "prodotti.detail.projects.cta", defaultValue: "Esplora le realizzazioni →" },
      { key: "prodotti.detail.support.label", defaultValue: "Supporto ai professionisti" },
      { key: "prodotti.detail.support.title", defaultValue: "Hai un progetto contract\nda realizzare?" },
      { key: "prodotti.detail.support.description", defaultValue: "Collabora con il nostro team per sviluppare progetti unici che soddisfino le esigenze del tuo cliente." },
      { key: "prodotti.detail.support.feature1", defaultValue: "Dimensioni personalizzate dei prodotti" },
      { key: "prodotti.detail.support.feature2", defaultValue: "Finiture differenti dallo standard" },
      { key: "prodotti.detail.support.feature3", defaultValue: "Realizzazione modelli non a catalogo" },
      { key: "prodotti.detail.support.cta", defaultValue: "Contattaci per il tuo progetto →" },
      { key: "prodotti.detail.model_2d", defaultValue: "Modello 2D" },
      { key: "prodotti.detail.model_3d", defaultValue: "Modello 3D" },
      { key: "prodotti.detail.show_more", defaultValue: "Continua a leggere" },
      { key: "prodotti.detail.show_less", defaultValue: "Mostra meno" },
      { key: "prodotti.detail.variants", defaultValue: "Varianti" },
      { key: "prodotti.detail.find_store", defaultValue: "Cerca un punto vendita" },
      { key: "prodotti.detail.tech_section_title", defaultValue: "Scheda tecnica, 2D, 3D, istruzioni d'uso, manutenzione" },
      { key: "prodotti.detail.tech_sheet_download", defaultValue: "Scheda tecnica" },
      { key: "prodotti.detail.dims_unavailable", defaultValue: "Dimensioni non disponibili." },
      { key: "prodotti.detail.custom.title", defaultValue: "Dimensioni personalizzate dei prodotti" },
      { key: "prodotti.detail.custom.cta", defaultValue: "Contattaci per il tuo progetto" },
    ],
  },
  {
    id: "progetti",
    label: "Pagina Progetti",
    strings: [
      { key: "progetti.title", defaultValue: "Progetti" },
      { key: "progetti.description.line1", defaultValue: "Uno sguardo sulle nostre realizzazioni nel mondo." },
      { key: "progetti.description.line2", defaultValue: "Dai bistrot più ricercati agli hotel d'avanguardia, dagli spazi culturali ai contesti residenziali, i nostri arredi contribuiscono a definire atmosfere inconfondibili." },
      { key: "progetti.description.line3", defaultValue: "In questa sezione raccogliamo una selezione di progetti che raccontano come la nostra estetica e la nostra storia si intrecciano con le visioni di architetti e interior designer contemporanei." },
      { key: "progetti.filter.all", defaultValue: "Tutti" },
      { key: "progetti.filter.country", defaultValue: "Filtra per Paese" },
      { key: "progetti.filter.product", defaultValue: "Filtra per prodotto" },
      { key: "progetti.empty", defaultValue: "Nessun progetto trovato per questa selezione." },
      { key: "progetti.breadcrumb", defaultValue: "Progetti" },
      { key: "progetti.detail.not_found", defaultValue: "Progetto non trovato" },
      { key: "progetti.detail.back", defaultValue: "Torna ai progetti" },
      { key: "progetti.detail.show_more", defaultValue: "Continua a leggere" },
      { key: "progetti.detail.show_less", defaultValue: "Mostra meno" },
      { key: "progetti.detail.label.project", defaultValue: "Progetto" },
      { key: "progetti.detail.label.photo_by", defaultValue: "Foto da" },
      { key: "progetti.detail.label.location", defaultValue: "Location" },
      { key: "progetti.detail.products_used", defaultValue: "Prodotti utilizzati nel progetto" },
    ],
  },
  {
    id: "campagne-video",
    label: "Pagina Campagne & Video",
    strings: [
      { key: "campagne-video.title", defaultValue: "Campagne & Video" },
      { key: "campagne-video.filter.all", defaultValue: "Tutti" },
      { key: "campagne-video.empty", defaultValue: "Nessuna campagna trovata per questa selezione." },
      { key: "campagne-video.breadcrumb", defaultValue: "Campagne & Video" },
      { key: "campagne-video.detail.related", defaultValue: "Altre Campagne e Video" },
    ],
  },
  {
    id: "news",
    label: "Pagina News & Rassegna Stampa",
    strings: [
      { key: "news.title", defaultValue: "News & Rassegna Stampa" },
      { key: "news.detail.continue", defaultValue: "Continua a leggere" },
      { key: "news.filter.all", defaultValue: "Tutti" },
      { key: "news.empty", defaultValue: "Nessun articolo trovato per questa selezione." },
      { key: "news.breadcrumb", defaultValue: "News & Rassegna Stampa" },
    ],
  },
  {
    id: "professionisti",
    label: "Professionisti (intro)",
    strings: [
      { key: "professionisti.title", defaultValue: "Professionisti" },
      { key: "professionisti.description", defaultValue: "Gebrüder Thonet Vienna mette a disposizione di architetti, interior designer e progettisti gli strumenti per supportare ogni fase del lavoro: cataloghi completi della collezione, materiali tecnici per la specifica di prodotto e il servizio di realizzazione di soluzioni su misura per progetti contract, hospitality e residenziali." },
      { key: "professionisti.breadcrumb", defaultValue: "Professionisti" },
    ],
  },
  {
    id: "cataloghi",
    label: "Professionisti — Cataloghi",
    strings: [
      { key: "cataloghi.title", defaultValue: "Cataloghi" },
      { key: "cataloghi.magazine.title", defaultValue: "Slow Living Magazine" },
      { key: "cataloghi.breadcrumb", defaultValue: "Cataloghi" },
    ],
  },
  {
    id: "materiale-tecnico",
    label: "Professionisti — Materiale Tecnico",
    strings: [
      { key: "materiale-tecnico.models.tab", defaultValue: "Modelli 2D e 3D" },
      { key: "materiale-tecnico.sheets.tab", defaultValue: "Schede Tecniche" },
      { key: "materiale-tecnico.sheets.title", defaultValue: "Schede Tecniche" },
      { key: "materiale-tecnico.models.title", defaultValue: "Modelli 2D e 3D" },
      { key: "materiale-tecnico.empty", defaultValue: "Nessun file disponibile." },
      { key: "materiale-tecnico.download.label", defaultValue: "Download" },
      { key: "materiale-tecnico.breadcrumb", defaultValue: "Materiale Tecnico" },
    ],
  },
  {
    id: "realizzazioni-custom",
    label: "Professionisti — Realizzazioni Custom",
    strings: [
      { key: "realizzazioni-custom.title", defaultValue: "Realizzazioni Custom" },
      { key: "realizzazioni-custom.description", defaultValue: "GTV mette il proprio know-how al servizio di architetti e designer per realizzazioni su misura. Dallo sviluppo di finiture esclusive alla creazione di arredi personalizzati, offriamo soluzioni su misura per progetti contract e residenziali. Contattaci per una consulenza dedicata." },
      { key: "realizzazioni-custom.cta", defaultValue: "Scrivici →" },
      { key: "realizzazioni-custom.breadcrumb", defaultValue: "Realizzazioni Custom" },
    ],
  },
  {
    id: "contatti",
    label: "Pagina Contatti",
    strings: [
      { key: "contatti.title", defaultValue: "Contatti" },
      { key: "contatti.description", defaultValue: "Scegli la sezione più adatta alla tua richiesta: la rete vendita per individuare il punto di acquisto più vicino, le collaborazioni per proporci nuovi progetti di design, l'ufficio stampa per i media, la richiesta informazioni per qualunque altra domanda e le landing page dedicate ai nostri eventi." },
      { key: "contatti.breadcrumb", defaultValue: "Contatti" },
    ],
  },
  {
    id: "collaborazioni",
    label: "Contatti — Collaborazioni",
    strings: [
      { key: "collaborazioni.hero.title", defaultValue: "Collaborazione nuovi designer" },
      { key: "collaborazioni.intro", defaultValue: "GTV è sempre alla ricerca di nuove visioni e talenti nel design. Se desideri collaborare con noi e proporre le tue idee, inviaci la tua candidatura attraverso il form sottostante. Siamo pronti a esplorare insieme nuove possibilità." },
      { key: "collaborazioni.success.title", defaultValue: "Grazie!" },
      { key: "collaborazioni.success.message", defaultValue: "La tua candidatura è stata inviata con successo." },
      { key: "collaborazioni.submit.label", defaultValue: "Invia i tuoi dati" },
      { key: "collaborazioni.form.firstName", defaultValue: "Nome" },
      { key: "collaborazioni.form.lastName", defaultValue: "Cognome" },
      { key: "collaborazioni.form.email", defaultValue: "Indirizzo email" },
      { key: "collaborazioni.form.company", defaultValue: "Nome dello studio" },
      { key: "collaborazioni.form.vatNumber", defaultValue: "Partita IVA" },
      { key: "collaborazioni.form.notes", defaultValue: "Altre informazioni" },
      { key: "collaborazioni.form.notes.placeholder", defaultValue: "Hai qualcosa da aggiungere? Inserisci qui le tue note" },
      { key: "collaborazioni.form.privacy", defaultValue: "Conferma di aver preso visione dell'informativa della Privacy e sull'utilizzo dei dati personali" },
      { key: "collaborazioni.form.profiling", defaultValue: "Presto il consenso per le attività di profilazione" },
      { key: "collaborazioni.error.privacy", defaultValue: "Devi accettare la privacy policy per inviare il messaggio." },
      { key: "collaborazioni.error.profiling", defaultValue: "Devi accettare la profilazione per inviare il messaggio." },
      { key: "collaborazioni.breadcrumb", defaultValue: "Collaborazione nuovi designer" },
    ],
  },
  {
    id: "rete-vendita",
    label: "Contatti — Rete di Vendita",
    strings: [
      { key: "rete-vendita.hero.title", defaultValue: "Rete di vendita" },
      { key: "rete-vendita.tab.store", defaultValue: "Negozio" },
      { key: "rete-vendita.tab.agent", defaultValue: "Agenti e Distributori" },
      { key: "rete-vendita.search.label", defaultValue: "Trova il punto vendita più vicino a te" },
      { key: "rete-vendita.search.placeholder", defaultValue: "Roma, RM, Italia" },
      { key: "rete-vendita.search.button", defaultValue: "Avvia la ricerca" },
      { key: "rete-vendita.results.text", defaultValue: "CI SONO" },
      { key: "rete-vendita.results.near", defaultValue: "PUNTI VENDITA VICINO A" },
      { key: "rete-vendita.empty", defaultValue: "Nessun risultato" },
      { key: "rete-vendita.contact.button", defaultValue: "Contattaci" },
      { key: "rete-vendita.modal.title", defaultValue: "Contatta" },
      { key: "rete-vendita.modal.success.title", defaultValue: "Messaggio inviato!" },
      { key: "rete-vendita.modal.success.message", defaultValue: "Ti risponderanno il prima possibile." },
      { key: "rete-vendita.modal.submit", defaultValue: "Invia messaggio" },
      { key: "rete-vendita.modal.submitting", defaultValue: "Invio..." },
      { key: "rete-vendita.form.reason", defaultValue: "Motivo del contatto" },
      { key: "rete-vendita.form.privacy", defaultValue: "Accetto la privacy policy" },
      { key: "rete-vendita.form.newsletter", defaultValue: "Desidero ricevere aggiornamenti e novità" },
    ],
  },
  {
    id: "richiesta-info",
    label: "Contatti — Richiesta Informazioni",
    strings: [
      { key: "richiesta-info.title", defaultValue: "Richiesta Informazioni" },
      { key: "richiesta-info.description", defaultValue: "Hai domande sui nostri prodotti o servizi? Il nostro team è a tua disposizione per fornirti tutte le informazioni di cui hai bisogno. Contattaci e saremo lieti di rispondere alle tue richieste nel più breve tempo possibile." },
      { key: "richiesta-info.cta", defaultValue: "Contattaci →" },
      { key: "richiesta-info.breadcrumb", defaultValue: "Richiesta Informazioni" },
    ],
  },
  {
    id: "ufficio-stampa",
    label: "Contatti — Ufficio Stampa",
    strings: [
      { key: "ufficio-stampa.title", defaultValue: "Ufficio Stampa" },
      { key: "ufficio-stampa.intro", defaultValue: "Per materiali stampa, interviste o altre informazioni ufficiali, contattateci a:" },
      { key: "ufficio-stampa.agency", defaultValue: "Agence Melchior" },
      { key: "ufficio-stampa.contact1.name", defaultValue: "Debora Agostini:" },
      { key: "ufficio-stampa.contact2.name", defaultValue: "Allegra Emilia Amatori:" },
      { key: "ufficio-stampa.breadcrumb", defaultValue: "Ufficio Stampa" },
    ],
  },
];

export const UI_STRINGS_BY_KEY: Record<string, UiStringDef> = UI_STRING_GROUPS.reduce(
  (acc, g) => {
    for (const s of g.strings) acc[s.key] = s;
    return acc;
  },
  {} as Record<string, UiStringDef>
);

export function getDefaultString(key: string): string {
  return UI_STRINGS_BY_KEY[key]?.defaultValue ?? key;
}
